stages:
  - install
  - build
  - test
  - deploy

variables:
  # Use Node.js version you prefer (make sure to use the right version)
  NODE_VERSION: "16"  # Example: Node.js 16.x

before_script:
  - npm install -g npm@latest  # Make sure npm is up to date

install_dependencies:
  stage: install
  image: node:16  # Use a Docker image with Node.js pre-installed
  script:
    - npm install  # Install dependencies from package.json

build_project:
  stage: build
  tags: 
   - docker
  image: node:16
  script:
    - cd client-ui
    - npm run build  # Build the Vue.js app with Vite

run_tests:
  stage: test
  tags: 
   - docker
  image: node:16

deploy_project:
  stage: deploy
  tags:
    - docker
  image: ruby:alpine
  script:
    - apk update && apk add git curl
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  environment:
    name: production
    url: https://$HEROKU_APP_NAME.herokuapp.com/
  only:
    refs:
      - master
    variables:
      - $HEROKU_APP_NAME
      - $HEROKU_API_KEY


