image: node:22-alpine  # Use Alpine-based image with Node.js 22

stages:
  - install
  - test
  - build
  - deploy

variables:
  # Use Node.js version you prefer (make sure to use the right version)
  NODE_VERSION: "22"  # Example: Node.js 16.x

install_dependencies:
  stage: install
  tags: 
   - docker
  script:
    - apk add --no-cache nodejs npm  # Install Node.js and npm in Alpine image
    - cd client
    - npm ci  # Use ci for clean installatio

# New test stage
test:
  stage: test
  tags:
    - docker
  script:
    - cd coreServices
    - cd TimeslotsService
    - npm ci  # Ensure dependencies are installed in the timeslot folder
    - npm install
    - npm test  # Run tests (ensure your package.json has the test script configured)
    - cd coreServices
    - cd OfficesService
    - npm ci
    - npm install
    - npm test
    - cd coreServices
    - cd userManagementService
    - npm ci
    - npm install
    - npm test


build:
  stage: build
  tags: 
   - docker
  script:
    - cd client
    - npm install
    - npm run build  # Build the Vue.js app with Vite

deploy:
  stage: deploy
  tags:
    - docker
  script:
   - cd client
   - npm install
 
     


