

stages:
  - install
  - build
  - deploy

variables:
  # Use Node.js version you prefer (make sure to use the right version)
  NODE_VERSION: "22"  # Example: Node.js 16.x

install_dependencies:
  stage: install
  tags: 
   - docker
  image: node:22  # Use a Docker image with Node.js pre-installed
  script:
    - cd client-ui
    - npm install  # Install dependencies from package.json

build_project:
  stage: build
  tags: 
   - docker
  image: node:22
  script:
    - cd client-ui
    - npm run build  # Build the Vue.js app with Vite

deploy_project:
  stage: deploy
  tags:
    - docker
  script:
   - cd client-ui
   - npm install
 
     


